ssl: introduce SSLEngineConfigurator#setSSLParameters
eclipse-ee4j/glassfish-grizzly pull request #2054
Opened 2019-04-10 15:34 UTC by kofemann

SSLParameters is a class introduced in java6 which can take over
SSLEngineConfigurator. As a first step, let allow applications to
use SSLParameters to configure SSLEngineConfigurator.

2019-04-10 19:16 UTC, bshannon approved these changes
I suppose this is fine, although it's interesting that SSLParameters supports a lot of
options that are ignored here, and SSLEngine can take an SSLParamaters object
directly, but that isn't done here.  I suspect this code should be updated to handle
additions to SSLEngine in JDK 1.7 and 1.8.

2019-04-10 20:33 UTC, kofemann commented
As mentioned in the commit message, this can be the first step. The SSLEngineConfigurator can be updated to build SSLParamaters and then use it when SSLEngineConfigurator#configure method is called. This will make code much simple.

2019-04-11 19:15 UTC, arjantijms requested changes

2019-04-11 19:15 UTC, arjantijms commented on modules/grizzly/src/main/java/org/glassfish/grizzly/ssl/SSLEngineConfigurator.java
> +     * Apply {@link SSLParameters} to this SSLEngineConfigurator.
> Apply {@link SSLParameters} to this SSLEngineConfigurator.

Might want to document that only the cipherSuites, protocols, needClientAuth and wantClientAuth properties are applied?

2019-04-12 20:32 UTC, kofemann commented
may be make sense to squash this two commits...

2023-08-24 17:35 UTC, mnriem commented
@kofemann Have you applied the requested changes?

2023-08-24 17:43 UTC, kofemann commented
Are people interested in this changes? In general, looks like grizzly project has very low activity since eclipse took over.

2023-08-24 19:23 UTC, arjantijms commented
> Are people interested in this changes? In general, looks like grizzly project has very low activity since eclipse took over.

We definitely have a low amount of resources to work on Grizzly, which is really unfortunate :(

2023-08-24 19:24 UTC, arjantijms approved these changes
Let's forget about the requested changes

2023-08-24 20:21 UTC, kofemann commented
Ok. Let me rebase and retest. I will update the PR.

2023-08-30 13:40 UTC, mnriem commented
@arjantijms  Looks good to me

2023-08-30 13:54 UTC, merged