Finer configuration of GZIP Compression
eclipse-ee4j/glassfish-grizzly pull request #2143
Opened 2021-10-28 14:57 UTC by JamesHillyard

Allows for finer configuration of GZIP Compression by setting the compression level and strategy. 

Tested on Windows 10 JDK 8

2021-12-14 15:26 UTC, MattGill98 requested changes

2021-12-14 15:26 UTC, MattGill98 commented on modules/grizzly/src/main/java/org/glassfish/grizzly/compression/zip/GZipEncoder.java
> +    private static int compressionLevel;
As these are configured through a constructor, they shouldn't be static

2022-06-10 22:32 UTC, arjantijms commented on modules/grizzly/src/main/java/org/glassfish/grizzly/compression/zip/GZipEncoder.java
> +    private static int compressionLevel;
@JamesHillyard @MattGill98 any chance to get this resolved?

2022-06-20 14:35 UTC, JamesHillyard commented on modules/grizzly/src/main/java/org/glassfish/grizzly/compression/zip/GZipEncoder.java
> +    private static int compressionLevel;
Hi @arjantijms, thanks for reminding me about this, I'll aim to get these changes done before the end of the week ready for another review

2022-07-04 14:23 UTC, arjantijms approved these changes

2022-07-05 10:29 UTC, MattGill98 approved these changes

2022-07-05 10:30 UTC, merged